version: '3.8'

services:
  db:
    build: ./db
    env_file:
      - ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$DB_DATABASE
    ports:
      - $DB_LOCAL_PORT:$DB_DOCKER_PORT
    restart: always
  app:
    depends_on:
      - db
    build: ./server/
    restart: always
    env_file:
      - ./.env
    ports:
      - $NODE_PORT:$NODE_PORT
    environment:
      - DB_HOST=db
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_DATABASE
      - DB_PORT=$DB_DOCKER_PORT
    stdin_open: true
    tty: true
volumes:
  db: